name: Companions
main: sxworz\pets\Main

api: 5.0.0 
version: 2.0.0

author: https://github.com/luckpickme/companios
description: Companion Plugin for PocketMine-MP 5.0.0

depend:
  - PurePerms
  - EconomyAPI

commands:
  companion:
    description: Компаньоны
    permission: companion.use
permissions:
  companion.use:
    default: true

