name: Companions
main: Companion\Pets\Main

api: 5.0.0 
version: 1.0.0

author: https://github.com/luckpickme/companions (pluginsplanet, luckpickme)
description: rewritten to pmmp5 by luckpickme
commands:
  companion:
    description: Компаньоны
    permission: companion.use
permissions:
  companion.use:
    default: true
depend:
  - PurePerms
  - FormAPI
  - EconomyAPI
